groups:
- name: prometheus_rules
  rules:
    - alert: PrometheusTargetMissing
      expr: up == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Prometheus target missing (instance {{ $labels.instance }})
        description: A Prometheus target has disappeared. An exporter might be crashed.\n VALUE is {{ $value }}\n LABELS are {{ $labels }}

    - alert: PrometheusAllTargetsMissing
      expr: count by (job) (up) == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Prometheus all targets missing (instance {{ $labels.instance }})
        description: A Prometheus job does not have living target anymore.\n VALUE is {{ $value }}\n LABELS are {{ $labels }}

    - alert: PrometheusConfigurationReloadFailure
      expr: prometheus_config_last_reload_successful != 1
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Prometheus configuration reload failure (instance {{ $labels.instance }})
        description: Prometheus configuration reload error\n VALUE is {{ $value }}\n LABELS are {{ $labels }}

    - alert: PrometheusTooManyRestarts
      expr: changes(process_start_time_seconds{job=~"prometheus|pushgateway|alertmanager"}[15m]) > 2
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Prometheus too many restarts (instance {{ $labels.instance }})
        description: Prometheus has restarted more than twice in the last 15 minutes. It might be crashlooping.\n VALUE is {{ $value }}\n LABELS are {{ $labels }}

    - alert: PrometheusAlertmanagerConfigurationReloadFailure
      expr: alertmanager_config_last_reload_successful != 1
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Prometheus AlertManager configuration reload failure (instance {{ $labels.instance }})
        description: AlertManager configuration reload error\n VALUE is {{ $value }}\n LABELS are {{ $labels }}

    - alert: PrometheusAlertmanagerConfigNotSynced
      expr: count(count_values("config_hash", alertmanager_config_hash)) > 1
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Prometheus AlertManager config not synced (instance {{ $labels.instance }})
        description: Configurations of AlertManager cluster instances are out of sync\n VALUE is {{ $value }}\n LABELS are {{ $labels }}

    - alert: PrometheusNotConnectedToAlertmanager
      expr: prometheus_notifications_alertmanagers_discovered < 1
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Prometheus not connected to alertmanager (instance {{ $labels.instance }})
        description: Prometheus cannot connect the alertmanager\n VALUE is {{ $value }}\n LABELS are {{ $labels }}

    - alert: PrometheusRuleEvaluationFailures
      expr: increase(prometheus_rule_evaluation_failures_total[3m]) > 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Prometheus rule evaluation failures (instance {{ $labels.instance }})
        description: Prometheus encountered {{ $value }} rule evaluation failures, leading to potentially ignored alerts.\n VALUE is {{ $value }}\n LABELS are {{ $labels }}

    - alert: PrometheusRuleEvaluationSlow
      expr: prometheus_rule_group_last_duration_seconds > prometheus_rule_group_interval_seconds
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Prometheus rule evaluation slow (instance {{ $labels.instance }})
        description: Prometheus rule evaluation took more time than the scheduled interval. It indicates a slower storage backend access or too complex query.\n VALUE is {{ $value }}\n LABELS are {{ $labels }}

    - alert: PrometheusAlertmanagerNotificationFailing
      expr: rate(alertmanager_notifications_failed_total[1m]) > 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Prometheus AlertManager notification failing (instance {{ $labels.instance }})
        description: Alertmanager is failing sending notifications\n VALUE is {{ $value }}\n LABELS are {{ $labels }}

    - alert: PrometheusTargetEmpty
      expr: prometheus_sd_discovered_targets == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Prometheus target empty (instance {{ $labels.instance }})
        description: Prometheus has no target in service discovery\n VALUE is {{ $value }}\n LABELS are {{ $labels }}

    - alert: PrometheusTargetScrapingSlow
      expr: prometheus_target_interval_length_seconds{quantile="0.9"} > 60
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Prometheus target scraping slow (instance {{ $labels.instance }})
        description: Prometheus is scraping exporters slowly\n VALUE is {{ $value }}\n LABELS are {{ $labels }}

    - alert: PrometheusLargeScrape
      expr: increase(prometheus_target_scrapes_exceeded_sample_limit_total[10m]) > 10
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Prometheus large scrape (instance {{ $labels.instance }})
        description: Prometheus has many scrapes that exceed the sample limit\n VALUE is {{ $value }}\n LABELS are {{ $labels }}

    - alert: PrometheusTargetScrapeDuplicate
      expr: increase(prometheus_target_scrapes_sample_duplicate_timestamp_total[5m]) > 0
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Prometheus target scrape duplicate (instance {{ $labels.instance }})
        description: Prometheus has many samples rejected due to duplicate timestamps but different values\n VALUE is {{ $value }}\n LABELS are {{ $labels }}